config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users,only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
  end

  resources :books,only: [:show,:index,:edit,:update,:destroy,:create] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create]
  end
  resources :book_comments, only: [:destroy]

  root 'home#top'
  get 'home/about'
  get '/search', to: 'search#search'
  # post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  # post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!,only: [:create,:edit,:update,:destroy,:index]
  
	def index
	  @books = Book.all
	  @book = Book.new
	end
  
	def show
	  @book = Book.find(params[:id])
	  @book_comment = BookComment.new
	  @book_comments = @book.book_comments
	  @books = Book.all
	end
  
	def edit
	  @book = Book.find(params[:id])
	  screen_user(@book)
	end
  
	def create
	  @book = Book.new(book_params)
	  @book.user_id = current_user.id
	  if @book.save
		redirect_to @book
	  else
		@books = Book.all
		render 'index'
	  end
	end
  
	def update
	  @book = Book.find(params[:id])
	  if @book.update(book_params)
		redirect_to @book
	  else
		render 'edit'
	  end
	end
  
	def destroy
	  @book = Book.find(params[:id])
	  @book.destroy
	  redirect_to books_url
	end
  
	private
	  def book_params
		params.require(:book).permit(:title, :body)
	  end
  
	  def screen_user(book)
		if book.user.id != current_user.id
		  redirect_to books_path
		end
	  end
  
  end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<td>
  <%= link_to(book.user) do %>
    <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
  <% end %>
</td>
<td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
<td><%= book.body %></td>

<td>
  <% if book.favorited_by?(current_user) %>
    <%= link_to book_favorites_path(book, redirect_id: 0), method: :delete, remote: true do %>
      
      <span class="glyphicon glyphicon-heart"><%= book.favorites.count%></span>
    <% end %>
  <% else %>
    <%= link_to book_favorites_path(book, redirect_id: 0), method: :post, remote: true do %>
      
      <span class="glyphicon glyphicon-heart-empty"><%= book.favorites.count %></span>
    <% end %>
  <% end %>
</td>
<td>コメント数：<%= book.book_comments.count %></td>

app/views/books/_comment.html.erb
<% book_comments.each do |book_comment| %> 
  <tr>
    <td>
      <%= link_to user_path(book_comment.user), class: "user_#{book_comment.user.id}" do %>
        <%= attachment_image_tag book_comment.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: "50x50" %><br>
        <%= book_comment.user.name %>
      <% end %>
    </td>
    <td><%= book_comment.comment %></td>
    <% if book_comment.user == current_user %>
      <td><%= link_to 'Destroy', book_comment_path(book_comment), class: 'btn-sm btn-danger', method: :delete, remote: true %></td>
    <% end %>
  </tr>
<% end %>

app/views/books/_detail.html.erb
<td><%= link_to(book.user) do %>
  <%= attachment_image_tag(book.user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg") %><br>
  <%= book.user.name %>
  <% end %>
</td>
<td><%= link_to book.title, book %></td>
<td><%= book.body %></td>
<!-- いいね機能 -->
<td>
  <% if book.favorited_by?(current_user) %>
    <%= link_to book_favorites_path(book, redirect_id: 0), method: :delete, remote: true do %>
      <span class="glyphicon glyphicon-heart"><%= book.favorites.count%></span>
    <% end %>
  <% else %>
    <%= link_to book_favorites_path(book, redirect_id: 0), method: :post, remote: true do %>
      <span class="glyphicon glyphicon-heart-empty"><%= book.favorites.count %></span>
    <% end %>
  <% end %>
</td>
<td>コメント数：<%= book.book_comments.count %></td>

<% if book.user == current_user %>
  <td><%= link_to 'Edit', edit_book_path(book), class: "btn-sm btn-success edit_book_#{book.id}" %></td>
  <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn-sm btn-danger destroy_book_#{book.id}"%></td>
<% end %>

app/views/books/_form.html.erb
<%= form_for(book) do |f| %>
  <div class="field row">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'col-xs-12 book_title' %>
  </div>

  <div class="field row">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'col-xs-12 book_body'%>
  </div>

  <div class="actions row">
    <%= f.submit class: 'btn btn-primary col-xs-12'%>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr> 
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% books.each do |book| %>
      <tr class="like_<%= book.id %>">
        <%= render '/books/book', book: book %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='row'>
	<div class='col-md-6 col-md-offset-3'>
		<h1>Editing Book</h1>
  <!-- <div class='col-md-3 col-md-offset-3'>
  </div> -->
  	<%= render 'layouts/errors', obj: @book %>
		<%= render 'form', book: @book %>
		<%= link_to 'Show', @book, class: "book_#{@book.id}" %> |
		<%= link_to 'Back', books_path, class: "back" %>
    </div>
    <div class='col-md-3'></div>
</div>

app/views/books/index.html.erb
<%= render 'layouts/errors', obj: @book %>

<div class='row'>
  <div class='col-xs-3'>
    <h2>User info</h2>
    <%= render 'users/info', user: current_user %>

    <h2>New book</h2>
    <%= render 'form', book: @book %>
  </div>

  <div class='col-xs-9'>
    <h2>Books</h2>

    <%= render 'index', books: @books%>
  </div>
</div>

app/views/books/show.html.erb
<div class='row'>
  <div class='col-xs-3'>
    <h2>User info</h2>
      <%= render 'users/info', user: @book.user %>
    <h2>New book</h2>
      <%= render '/books/form', book: Book.new %>
  </div>
  

  <div class='col-xs-9'>
		<h2>Book detail</h2>
		<table class='table'>
      <tr class="book_<%= @book.id %>">
        <%= render 'detail', book: @book %>
      </tr>
    </table>
     <table class="show-tb comment_<%= @book.id %>">
      <%= render 'comment', book_comments: @book.book_comments %>
    </table>
    <div class="comment-form">
      <%= form_with model:[@book, @book_comment], data: {remote: true} do |f| %>
        <%= f.text_area :comment, size: "90x5" %>
        <%= f.submit '送信' %>
      <% end %>
    </div>
  </div>
</div>